# Generated by Django 2.0.6 on 2019-05-27 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20190527_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.IntegerField(),
        ),
    ]
